---
title: "Acidification of Peatland Bogs in Alberta, Canada: Influences of Oil Sands Development on peat cycle"
author: "Isabella Duggan"
output:
  quarto::pdf_document:
    citation_package: natbib
    latex_engine: pdflatex
    template: apa6
bibliography: sources/references_bib/references_bib.bib
---

Research Paper Outline: 

1. Title Page 

2. Acknowledgements 

3. Table of Contents 

4. Abstract 

5. Biography 

6. Overview 

  * Peat bogs:
  
   > Introduction
  What are peatlands (1-2 pages)
Peatland habitat covers approximately 365,157 km^2 of land in western Canada (Wieder et al., 2021; Vitt et al., 2000). These ecosystems are known for their carbon sequestration from the atmosphere and are often referred to as carbon sinks(), though they are not limited to only drawing carbon from the atmosphere. Other greenhouse gasses, DEFINE, including nitrogen and sulfur, and their varying forms, are also commonly retained by peat in peatlands ().
There are varying forms of peatlands, typically minerotrophic fens and ombrotrophic bogs, where specific conditions allow for a variety of specialized species to dominate. While vegetation and species present are important to identifying peatland habitat, there are other classifications to consider in defining a peatland. Overarchingly, peatlands can be understood as a type of wetland where the water table is at or near the surface (Bogs & Fens book, Peatlands book), and can be distinguished from other wetlands by the presence of peat. Peat, made up of decomposing plant and animal matter, accumulates in the anoxic conditions of bogs and fens. Wetland habitat may be designated as peatland after peat has accumulated to 30 cm, or greater, depth (according to Canadian classification) (peatlands book). 
Minerotrophic fens (briefly). Ombrotrophic bogs. Bog cover
Peat is directly associated with carbon and other greenhouse gas sequestration from the atmosphere, and will hold onto these components unless disturbed or dredged ().

* Define peat/ importance of peat (peat deposits = LOTS of carbon); peat pulls carbon from atmosphere and holds onto it so long as we don’t dig it up. Peat grows at 1-2 mm per year, with depth in certain places it was around for 6000-8000 years.
  * Bogs versus fens
* Global bogs importance (?) (2 paragraphs)
  * Global coverage?
  * Carbon sink
  * Purpose of peat (reiterate)
* Specific to Canada (1 page)
  * Alberta
  * Alberta research
* C N and S deposition (2 pages)
  * Carbon sink
  * N and S processes
  * Thermodynamic ladder
* Research idea (4 pages? ~8 paragraphs)
  * Climate change
  * Factors and importance
  * Precipitation/ Water table
  * Temperature
  * Evapotranspiration????



@citation_key
